### ISSUE TITLE
更新全量包返回的data数据中path的地址需要在哪里配置？

### ISSUE THREAD

**Issue by mingxinyiriyi** [bmfe/eros-publish#3]
{
    // 此次请求有没有问题
    "resCode": 0,
    // 此次请求描述
    "msg": "当前版本已是最新，不需要更新",
    // 回溯的数据
    "data": {
        // 表示这是一个完整的包
        "diff": false,
        // 完整包的地址
        "path": "https://xxx.xxx.com/app/cd34091af113f98c2cbf4d81131ccdde.zip"
    }
}

**Comment by PerseveranceZ** [comment]
`config/dev.js`

**Comment by mingxinyiriyi** [comment]
请问怎么配置，confing/eros.dve.js文件吗？

**Comment by PerseveranceZ** [comment]
是的 这个文件 readme 里面说了 就是 diff 里面
