### ISSUE TITLE
MongDB版本是4.11.0无法启动项目

### ISSUE THREAD

**Issue by mingxinyiriyi** [bmfe/eros-publish#4]
mongdb4.11.0的版服务起不来， 启动eros-publish server 报错

(node:8356) DeprecationWarning: open() is deprecated in mongoose >= 4.11.0, use openUri() instead, or set the useMongoClient option if using connect() or createConnection(). See http://mongoosejs.com/docs/connections.html#use-mongo-client

网上的解决方案是mongoose.connect('mongodb://localhost/test',{useMongoClient:true})。但是不起作用

**Comment by PerseveranceZ** [comment]
@mingxinyiriyi 文档推荐的版本 会有问题吗

**Comment by PerseveranceZ** [comment]
警告而已
