### ISSUE TITLE
MongDB版本是3.4.9还是出现启动不起来的问题

### ISSUE THREAD

**Issue by mingxinyiriyi** [bmfe/eros-publish#5]
运行项目
------------------------------------------------------------------------------------
C:\java\eros-publish-master\eros-publish-master\server>supervisor app.js

Running node-supervisor with
  program 'app.js'
  --watch '.'
  --extensions 'node,js'
  --exec 'node'

Starting child process with 'node app.js'
Watching directory 'C:\java\eros-publish-master\eros-publish-master\server' for changes.
Press rs for restarting the process.
(node:10264) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
Server started on port 3001

------------------------------------------------------------------------------------
                                   mongodb的版本
------------------------------------------------------------------------------------
C:\Program Files\MongoDB\Server\3.4\bin>mongo -version
MongoDB shell version v3.4.9
git version: 876ebee8c7dd0e2d992f36a848ff4dc50ee6603e
allocator: tcmalloc
modules: none
build environment:
    distarch: x86_64
    target_arch: x86_64

**Comment by PerseveranceZ** [comment]
@mingxinyiriyi 
Server started on port 3001 
不是已经跑在3001了？

**Comment by mingxinyiriyi** [comment]
![1](https://user-images.githubusercontent.com/15307525/45871695-b43bf980-bdc0-11e8-99bc-2e2a77da5e6c.png)
这个都运行错误了

**Comment by PerseveranceZ** [comment]
我觉得你可以对热更新服务有误解
我只是提供了几个接口的 demo  具体你要什么页面 做什么权限 自己加 就行
